// External packages
import type { Metadata } from 'next';
import { twJoin } from 'tailwind-merge';

// Fonts
import { poppins } from '@/lib/fonts';

// Metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

//Global styles
import './globals.css';

// Components
import { Toast } from '@/components/ui/Toast';
import { AuthProvider } from '@/components/ui/AuthWrapper';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={twJoin(poppins.className, 'bg-gray-100')}>
        <AuthProvider>{children}</AuthProvider>
        <Toast />
      </body>
    </html>
  );
}
